# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt6 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Cadastrar(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.ImputDoc = QtWidgets.QLineEdit(Dialog)
        self.ImputDoc.setGeometry(QtCore.QRect(160, 150, 113, 22))
        self.ImputDoc.setObjectName("ImputDoc")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 30, 231, 16))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.ImputEndereco = QtWidgets.QLineEdit(Dialog)
        self.ImputEndereco.setGeometry(QtCore.QRect(160, 120, 113, 22))
        self.ImputEndereco.setObjectName("ImputEndereco")
        self.BtnCad = QtWidgets.QPushButton(Dialog)
        self.BtnCad.setGeometry(QtCore.QRect(60, 210, 75, 24))
        self.BtnCad.setObjectName("BtnCad")
        self.BtnCancelar = QtWidgets.QPushButton(Dialog)
        self.BtnCancelar.setGeometry(QtCore.QRect(170, 210, 75, 24))
        self.BtnCancelar.setObjectName("BtnCancelar")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 120, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 51, 21))
        self.label_2.setObjectName("label_2")
        self.ImputNome = QtWidgets.QLineEdit(Dialog)
        self.ImputNome.setGeometry(QtCore.QRect(160, 90, 113, 22))
        self.ImputNome.setObjectName("ImputNome")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 150, 91, 21))
        self.label_4.setObjectName("label_4")
        self.BtnLimpar = QtWidgets.QPushButton(Dialog)
        self.BtnLimpar.setGeometry(QtCore.QRect(280, 210, 75, 24))
        self.BtnLimpar.setObjectName("BtnLimpar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tela de Cadastro"))
        self.ImputDoc.setPlaceholderText(_translate("Dialog", "Insira seu documento"))
        self.label.setWhatsThis(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Cadastro usuario do Sistema</p></body></html>"))
        self.ImputEndereco.setPlaceholderText(_translate("Dialog", "Insira seu endereco"))
        self.BtnCad.setText(_translate("Dialog", "Cadastrar"))
        self.BtnCancelar.setText(_translate("Dialog", "Cancelar"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700;\">Endereco</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700;\">Nome</span></p></body></html>"))
        self.ImputNome.setPlaceholderText(_translate("Dialog", "Insira seu nome"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700;\">Documento</span></p></body></html>"))
        self.BtnLimpar.setText(_translate("Dialog", "Limpar"))
import tela

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Cadastrar()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())